services:
  - type: web
    name: PersonalProject
    env: docker
    plan: free
    buildCommand: docker build -t PersonalProject .
    runtime: docker
    startCommand: docker run -p 8080:8080 PersonalProject

